trailblazer/cells

lib/cell/railtie.rb

Using "const_defined?" without false as the second parameter also looks
for the constant in all ancestor classes. So when my app includes
the "haml" gem but not "cells-haml", it would still return true and
raise an exception because it cannot find the Cells module.

Use proper lookup when including template modules

---

lib/cell/railtie.rb
test/rails4.2/app/cells/form_for_cell.rb
test/rails4.2/app/cells/form_tag/show.erb
test/rails4.2/app/cells/form_tag_cell.rb
test/rails4.2/app/cells/formtastic_cell.rb
test/rails4.2/app/cells/simple_form_cell.rb
test/rails4.2/config/initializers/formtastic.rb
test/rails4.2/engines/my_engine/my_engine.gemspec
test/rails4.2/test/integration/form_tag_test.rb

```ruby
<%= "With all the love to rails helpers" do -%>
```
This adds `ActionView::Helpers::FormHelper` into the included by default rails helpers.
It allows to avoid overriding `Cell::Erb`'s `capture` re-implementation.
Also, as soon as `ActionView::Helpers::FormHelper` includes `UrlHelper` and `FormTagHelper` it's no need to include them once again.
It also fixes warnings in `test/rails4.2` test suite.
```ruby
<% end %>
```

Include ActionView::Helpers::FormHelper by default

---

lib/cell/partial.rb
test/partial_test.rb

My use case is that I need to have more that one view path and render a global partial within a cell. This is probably totally wrong but I'm upgrading an app with cells 3 to 4 and this was allowed before ;)
The thing is, when there is a in-place mangling with `view_paths` in `Partial` module (with `unshift`) it yields really ugly and unexpected results. And does not allow me to do what I want. I think it is a better idea to create a new array instead of `unshift`. Test case added.

Make Partial work with multiple view paths

---

test/i18n_test.rb

The relative-path test that expects Cells to set the path
currently generates an error but the others pass if that one
is commented out.
All tests should pass if Cells sets @virtual_path appropriately.

I18N tests for translations with absolute and relative paths

---

lib/cell/view_model.rb

`# TODO: cache template with path/lookup keys.` [source](https://github.com/apotonick/cells/blob/bee267927a607d1f847ebb1d3c8be597e5d99e4a/lib/cell/view_model.rb#L117)
Should here really a caching?
`find_template` calls `template_for` which calls `Templates#[]` which already caches.

discussion don't double cache

---

lib/cell/view_model.rb

**First case 'explizit render':**  Before this PR `#render` calls `caller` and give the result to `normalize_options`, which don't work with the `caller` when a explizit view name is used.
The PR makes this case ~25% faster
**Second case 'implizit render':** Before this PR the complete `caller` stack would be read, but we only need the last 2 segments. By only reading the 2 last segments, the `caller` call is faster and don't produce big arrays, which optimize the memory footprint.
The PR makes this case ~20% faster
Note: all test are based on this Cell, Model and View:
```ruby
model = "test"
class TestCell < Cell::ViewModel
def index
render
end
def index_explizit
render "index"
end
end
```
```erb
<%= model %>
```
I also remove the `TODO: speedup by not doing state_for_implicit_render.` …

Optimize render

---

test/rails_extensions_test.rb

> NoMethodError: undefined method `assert_equal' for nil:NilClass
You can reproduce the occasional failure reliably by running only `test/rails_extensions_test.rb`, ie. `rake test TEST=test/rails_extensions_test.rb`  This is because the `ctx` requires the rspec-style `describe` block and so is only accidentally set when the tests are all run together.
Switching back to (ahem, _proper_ :) `assert_*` style assertions fixes this.

Fixes occasional test failure.

---

.travis.yml
gemfiles/rails3.2.gemfile

Someone with write access will need to go to gitter to get the URL, you go here and click on Travis and grab the URL

Travis updates, ruby 2.2, head (allowed to fail) and gitter notification

---

lib/cell/view_model.rb

```
```
`alias_method` can't work here! `alias_method` creates a alias named alias to the *current* target method, but call would be overwritten by some modules. This results in the fact that `to_s` points to the original `call` method and not to the module overwrite one.

remove comment

---

lib/cell/railtie.rb

Here's a tiny patch that removes a Ruby warning.
There are several more unused block arguments that can be removed but I'm not gonna touch them here, because removing this `app` is enough for eliminating the warning.

⚠️ shadowing outer local variable - app

---

lib/cell/view_model.rb

The `Helpers` module is already `extend` some line above.

remove doubled include / extend

---

Gemfile
benchmarks/class_builder.rb
lib/cell.rb
lib/cell/builder.rb
lib/cell/view_model.rb
test/builder_test.rb

After some benchmarks I found out that the builder stuff cost ~45% of time for a cell.
```
Calculating -------------------------------------
ACell    25.710k i/100ms
ACellWithBuilder    19.948k i/100ms
-------------------------------------------------
ACell    419.631k (± 5.0%) i/s -      2.108M
ACellWithBuilder    291.924k (± 5.7%) i/s -      1.476M
Comparison:
ACell:   419630.8 i/s
ACellWithBuilder:   291923.5 i/s - 1.44x slower
```
Now it's extracted to a module to speed up a normal cell. 30% of the speed came from removing the builder from a basic Cell and 15% came from the `alias build new`, which optimize the hook.
NOTE: The Benchmark is included in this PR

extract builder support into a module

---

README.md

I was reading through the documentation and this seemed wrong. Please correct me if I'm wrong.

Correct typo in documentation under collections

---

lib/cell/concept.rb
lib/cell/view_model.rb
test/public_test.rb

`= concept "foo/bar"` can be: `= concept Foo::Bar` and also `= cell "foo/bar"` can be: `= cell Foo::BarCell`

Allow class in `concept` helper.

---

lib/cell/view_model.rb
test/cell_test.rb
test/fixtures/cell_test/song/show_with_block.erb

This is mostly a question instead of a PR to be merged (just because its easier to explain with ruby hahah)
my problem is, call a cell with any content to be included inside it, consider `BoldCell` that put any text inside a `<b></b>` tag
```ruby
BoldCell.new(nil).() do
"hello"
end
```
and returns
```html
<b>hello</b>
```
I wrote the test under `test/cell_test.rb` and modified to support this, but this is really ugly, specially the need for:
```ruby
def show_with_block(&block)
render do
block
end
end
```
on the cell 😿 
soooooo... whats the best way to do expected using _the cells way_ thank you!

Use render with a block

---

lib/cell/util.rb

`Util::constant_for` is used in `class_from_cell_name` to construct a class name
from the cell name.
It uses `const_get` to resolve constants, which by default will resolve
ancestors before descendants.
This fix passes `inherit = false` to `const_get` to ensure that it only
searches descendants.
This restores the 4.0.5 behaviour of `class_from_cell_name`.
Example:
The cell name is 'timesheets/client/overview', but Client is also the
name of an ActiveRecord model.
In 4.0.5 the resolved name would be `Timesheets::Client::Overview`
In 4.1.1 the resolved name is `Clients::Overview` (which is incorrect)
In 4.1.1 + this fix the resolved name is: `Timesheets::Client::Overview`

Util::constant_for only searches descendants

---

Rakefile
lib/cell/collection.rb
lib/cell/templates.rb
test/concept_test.rb
test/public_test.rb

Running `rake test` on the master branch generates a lot of noise. These changes suppress this noise, so you can focus on the status of the tests. I have made the following changes:
Suppress the built-in ruby warnings during testing. These warnings mostly contain messages like "warning: private attribute?" and "value xxx not initialized". There are several issues in the ruby bugtracker to fix this. To name a few:
- https://bugs.ruby-lang.org/issues/10967
- https://bugs.ruby-lang.org/issues/12299
Consider turning these warnings on again when these issues are resolved (and the associated ruby versions are widely distributed).
Replace the `File.exists` check with the equivalent, but non-deprecated `File.exist`. This was the only built-in warning that actually made sense.
Use the standard …

Clean up cells tests

---

lib/cell/util.rb

Assume that we have cell in Rails with name like this `Foo::Bar::BazCell` (`app/cells/foo/bar/baz_cell.rb`). If this class wasn't preloaded (in development) but class `Bar` was, then we get error `NameError: uninitialized constant Bar::BazCell`.

Change const getting by name

---

CHANGES.md
lib/cell/collection.rb
test/public_test.rb

Most of the time when I use `Collection#join`, I don't actually care about calling custom methods etc., I just want to stick some HTML in between each rendered cell. But `#join` insists on taking a block, so I have to do something like this:
my_collection.join('<hr>') { |cell| cell }
This PR makes the block optional, so I can just do it like this:
my_collection.join('<hr>')

Allow Collection#join to be used without a block

---

test/context_test.rb
test/templates_test.rb

When I run the tests on `master` with Minitest I get the following warning in a couple of places:
Use assert_nil if expecting nil from /Users/george/.rvm/gems/ruby-2.3.3/gems/minitest-5.10.1/lib/minitest/spec.rb:23:in `must_equal'. This will fail in MT6.
This PR updates the tests to remove the warnings.

Remove deprecated `must_equal(nil)` syntax from tests

---

cells.gemspec

If you clone from master and `bundle install` and cells-erb gets resolved to <
0.1.0, then a bunch of tests will fail (because the tested cells will render
strings with newlines on the end, but the tests don't expect the newline.)
Upgrading cells-erb to 0.1.0 fixes this. This PR makes the dependency explicit.
See also #451

bump cells-erb dev dependency to >= 0.1.0

---

README.md

This PR changes the build badges to point to `trailblazer`'s version, not `apotonick`'s.

README: Build badge point to trailblazer/cells

---

.travis.yml

Ruby 2.2 is reaching it's end of life at the end of the month. But I think it's useful to test recent Ruby versions as well.

Update tested Ruby version

---

README.md

The extra grave accent messes the formatting of the documentation in Cells 3, which I'm forced to use for now.
https://github.com/trailblazer/cells/blob/v3.11.3/README.md#using-decorators-twins

Fix the readme markup on Cells 3

---

lib/cell/templates.rb

Use Tilt::Cache instead of our own cache implementation
Tilt::Cache does exactly the same. Using that one cleans up our code significantly.

Tilt cache

---

cells.gemspec
lib/cell/caching.rb
lib/cell/option.rb
test/cache_test.rb

- Upgrade `declarative-builder` version (referring to the reported [issue](https://trailblazer.zulipchat.com/#narrow/stream/223924-general/topic/trailblazer-cells/near/240577894))
- Replace `declarative-option` with `trailblazer-option` as `declarative-builder` uses same.

Use trailblazer-option over declarative-option and upgrade declarative-builder

---

lib/cell/caching.rb
test/cache_test.rb

**Issue**
kwargs were not correctly getting forwarded to renderer in case of cache hit and it raised an exception in ruby3
**Fix**
Forward kwargs in ruby3 style!

Forward args in ruby3 style after cache hit

---

cells.gemspec

Add `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `homepage_uri`, `source_code_uri`, and `wiki_uri` to the gemspec metadata.
These [project metadata](https://guides.rubygems.org/specification-reference/#metadata) will facilitate easy access to project information. The URI will be available on the [Rubygems project page](https://rubygems.org/gems/cells), via the Rubygems API, and the `gem` and `bundle` command-line tools, after the next release.

Add project metadata to the gemspec
